# base settings
datamodule: ???
optimizer: ???

scheduler:
  _target_: lib.tracker.scheduler.OptimizerScheduler
  copy_optimizer_state: False
  milestones: ???
  params: ???

coarse2fine:
  _target_: lib.tracker.scheduler.CoarseToFineScheduler
  milestones: ???
  scales: ???

step_size:
  _target_: lib.tracker.scheduler.StepSizeScheduler
  milestones: ???
  factor: ???