# @package joint_tracker

defaults:
  - defaults
  - _self_ 

_target_: lib.tracker.tracker.JointTracker

# loop settings
init_idxs: [0,10,20,27,35,47,55,65,72,80]

max_iters: 150 
max_optims: 1
save_interval: 10

scheduler:
  milestones: [0,20]
  params: [[global_pose,transl],[neck_pose,shape_params,expression_params]]

coarse2fine:
  milestones: [0,70]
  scales: [8,4]

step_size:
  milestones: [0]
  factor: [1.0]