# @package joint_tracker

defaults:
  - defaults
  - _self_ 

_target_: lib.tracker.tracker.JointTracker

# loop settings
init_idxs: [0,20,35,47,55,65,72,80]

max_iters: 100
max_optims: 1
save_interval: 5

scheduler:
  milestones: [0,10]
  params: [[global_pose,transl],[neck_pose,shape_params,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]