# @package joint_tracker

defaults:
  - defaults
  - _self_ 

_target_: lib.tracker.tracker.JointTracker

# loop settings
init_idxs: [0,20,35,55,65,95,110,115]

max_iters: 80
max_optims: 10

scheduler:
  milestones: [0,10,20]
  params: [[global_pose,transl],[neck_pose],[shape_params,expression_params]]

# max_iters: 1
# max_optims: 1

# scheduler:
#   milestones: [0]
#   params: [[global_pose,transl]]

coarse2fine:
  milestones: [0]
  scales: [8]

default_params:
  transl: [0.0,0.0,-0.5]