# @package sequential_tracker

defaults:
  - defaults
  - _self_ 


_target_: lib.tracker.tracker.SequentialTracker

start_frame: null
end_frame: null
kernel_size: 1
stride: 1
dilation: 1

# loop settings
max_iters: 50
max_optims: 1
save_interval: 10

scheduler:
  milestones: [0]
  params: [[global_pose,transl,neck_pose,expression_params]]

coarse2fine:
  milestones: [0,20]
  scales: [8,4]

step_size:
  milestones: [0]
  factor: [1.0]