# @package sequential_tracker

defaults:
  - defaults
  - _self_ 


_target_: lib.tracker.tracker.SequentialTracker

# loop settings
kernel_size: 1
stride: 1
dilation: 1
start_frame: 0
end_frame: 120
max_iters: 30
max_optims: 5
# end_frame: 3
# max_iters: 5
# max_optims: 3

scheduler:
  milestones: [0]
  params: [[global_pose,transl,neck_pose,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]