# @package sequential_tracker

defaults:
  - defaults
  - _self_ 


_target_: lib.tracker.tracker.SequentialTracker

# loop settings
kernel_size: 1
stride: 1
dilation: 1
start_frame: 0

end_frame: 127
max_iters: 15
max_optims: 1
save_interval: 5

# end_frame: 1
# max_iters: 1
# max_optims: 1

scheduler:
  milestones: [0]
  params: [[global_pose,transl,neck_pose,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]