# @package weighting 

_target_: lib.model.weighting.UNetWeightModule
features: 64
depth: 3
mode: point_normal
max_weight: null 
size: 256
layer_norm: True 
final_activation: elu 
dummy_weight: False
device: ${device}