# @package residuals

_target_: lib.optimizer.residuals.ChainedResiduals
chain: 
  point2plane:
    _target_: lib.optimizer.residuals.Point2PlaneResiduals
    weight: 1.0
  # landmark:
  #   _target_: lib.optimizer.residuals.LandmarkResiduals
  #   weight: 1e-03
  # neck_regularization: 
  #   _target_: lib.optimizer.residuals.RegularizationResiduals
  #   name: neck_pose 
  #   weight: 1e-02  # 5e-03 
  shape_regularization: 
    _target_: lib.optimizer.residuals.RegularizationResiduals
    name: shape_params
    weight: 5e-03  # 5e-03 
  expression_regularization:
    _target_: lib.optimizer.residuals.RegularizationResiduals
    name: expression_params
    weight: 7e-04  # 7e-04