# @package residuals

_target_: lib.optimizer.residuals.ChainedResiduals
chain: 
  point2plane:
    _target_: lib.optimizer.residuals.Point2PlaneResiduals
    weight: 1.0
  expression_regularization: 
    _target_: lib.optimizer.residuals.NeuralRegularizationResiduals
    name: expression_params
    weight: 1e-03 
  transl_regularization: 
    _target_: lib.optimizer.residuals.NeuralRegularizationResiduals
    name: transl
    weight: 1e-03 
  global_pose_regularization: 
    _target_: lib.optimizer.residuals.NeuralRegularizationResiduals
    name: global_pose 
    weight: 1e-03
  neck_pose_regularization: 
    _target_: lib.optimizer.residuals.NeuralRegularizationResiduals
    name: neck_pose 
    weight: 1e-03