# @package residuals

_target_: lib.optimizer.residuals.ChainedResiduals
chain:
  point2plane:
    _target_: lib.optimizer.residuals.Point2PlaneResiduals
    weight: 1.0
  shape_regularization: 
    _target_: lib.optimizer.residuals.ShapeRegularizationResiduals
    weight: 5e-03
  expression_regularization:
    _target_: lib.optimizer.residuals.ExpressionRegularizationResiduals
    weight: 7e-04