# @package framework 

_target_: lib.optimizer.framework.WeightedOptimizer

flame: ???
logger: ???
renderer: ???
correspondence: ???
residuals: ???
optimizer: ???
weighting: ???

max_iters: 1
max_optims: 1
verbose: True 

lr: 1e-03
scheduler: null
params: [global_pose,transl,neck_pose,expression_params]
