# @package framework 

_target_: lib.optimizer.framework.WeightedOptimizer

flame: ???
logger: ???
renderer: ???
correspondence: ???
residuals: ???
optimizer: ???
weighting: ???

max_iters: 1
max_optims: 1
verbose: True 

lr: 1e-03
scheduler: null
params:
  global_pose: 1.0
  transl: 1.0
  neck_pose: 1.0
  expression_params: 1.0
