 # @package _global_

defaults:
  - data: synthetic
  - hydra: default
  - paths: default
  - _self_

seed: 123
device: cuda
task_name: train
tags: 
  - ${task_name}

model:
  _target_: lib.model.flame.Flame
  flame_dir: ${paths.root_dir}/checkpoints/flame2023_no_jaw
  shape_params: 100
  expression_params: 50
  vertices_mask: full
