# @package _global_

defaults:
  - model: flame 
  - logger: flame_wandb
  - data: flame # synthetic, kinect, debug, flame
  - residuals: neural  # face2face, neural 
  - optimizer:  gauss_newton 
  - framework : neural
  - correspondence: projective 
  - weighting: unet # dummy, cnn, unet
  - regularize: dummy # dummy, mlp
  - trainer: deterministic  # default, deterministic
  - callbacks: default
  - hydra: default
  - paths: default
  - _self_

# run setting 
train: True
eval: False
ckpt_path: ???

# base configs
seed: 123
device: cuda
task_name: train
tags: 
  - ${task_name}

# override framework settings
framework:
  max_iters: 1
  lr: 1e-04
  residual_weight: 0.01
  geometric_weight: 0.0
  param_weight: 1.0
  vertices_weight: 0.2

# override trainer settings
trainer:
  max_epochs: 2000  # 400
  accumulate_grad_batches: 64  # 8, 32 
  limit_train_batches: 256
