# @package _global_

defaults:
  - model: flame 
  - logger: flame_wandb
  - data: kinect_train   # synthetic, kinect_train
  - residuals: regularization 
  - optimizer: gauss_newton
  - framework : weighted_icp
  - correspondence: projective 
  - weighting: dummy 
  - hydra: default
  - paths: default
  - _self_

seed: 123
device: cuda
task_name: train
eval: False
train: True
tags: 
  - ${task_name}

framework:
  max_iters: 2
  max_optims: 1

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  accelerator: ${device}
  # training
  min_epochs: 1 
  max_epochs: 150
  # debugging
  overfit_batches: 1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 10
  log_every_n_steps: 1