# @package _global_

defaults:
  - model: flame 
  - logger: flame_wandb
  - data: kinect_train   # synthetic, kinect_train
  - residuals: regularization 
  - optimizer: gauss_newton
  - framework : weighted_icp
  - correspondence: projective 
  - weighting: residual # dummy, residual
  - hydra: default
  - paths: default
  - _self_

seed: 123
device: cuda
task_name: train
tags: 
  - ${task_name}

eval: False
train: True

# eval: True
# train: False

framework:
  lr: 1e-03
  max_iters: 1
  max_optims: 1
  params:
    global_pose: 1.0
    transl: 1.0
    neck_pose: 1.0
    expression_params: 1.0
  verbose: False

trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  accelerator: ${device}
  # training
  min_epochs: 1 
  max_epochs: 200
  # debugging
  overfit_batches: 32
  accumulate_grad_batches: 32
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  log_every_n_steps: 1