# @package model
_target_: lib.model.flame.FLAMEPoint2Point

# model settings
flame_dir: ${paths.root_dir}/checkpoints/flame2023
data_dir: ${data.data_dir}
num_shape_params: 100
num_expression_params: 50

# optimization settings
lr: 1e-03
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR 
  _partial_: True
  step_size: 200
  gamma: 0.5
optimize_frames: ${data.optimize_frames}
optimize_shapes: 1

save_interval: 1