# @package optimizer

_target_: lib.optimizer.newton.LevenbergMarquardt

# building the matrix A
mode: dynamic
max_damping_steps: 10
damping_factor: 1.0
factor: 2.0
levenberg: False

# step size
step_size: 1.0
line_search_fn: null

# store linear system
store_system: False
output_dir: ${paths.output_dir}/linsys

# Ax=b solver
# lin_solver:
#   _target_: lib.optimizer.pcg.PCGSolver
#   max_iter: 5
#   verbose: False
#   tol: 1e-08
#   mode: jaccobi 

lin_solver:
  _target_: lib.optimizer.pcg.PytorchSolver