# @package regularize 

_target_: lib.model.regularize.MLPRegularizeModule
features: 100
depth: 3
unet_features: ${weighting.features}
unet_depth: ${weighting.depth}
unet_size: ${weighting.size}
expression_params: ${model.expression_params}
shape_params: ${model.shape_params}