# @package scheduler

optimizer:
  _target_: lib.trainer.scheduler.OptimizerScheduler
  milestones: [0]
  params: [[global_pose,transl]]
  optimizer: levenberg_marquardt
  optimizer_params: null
  copy_optimizer_state: False