run:
  dir: ${paths.log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}
sweep:
  dir: ${paths.log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${task_name}
  subdir: ${hydra.job.num}

job_logging:
  formatters:
    simple:
      format: '%(asctime)s %(message)s'
      datefmt: '[%Y-%m-%d %H:%M:%S]'
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${task_name}.log