# @package trainer

# optimizer
optimizer: levenberg_marquardt
optimizer_params: ???
copy_optimizer_state: False

# logging settings
save_interval: 1

# convergence tests
check_convergence: False
convergence_threshold: 1e-10
min_tracker_steps: 2
max_tracker_steps: 5