# base settings
model: ???
datamodule: ???
logger: ???
loss: ???
camera: ???
rasterizer: ???

# logging settings
save_interval: 1
final_video: True

optimizer:
  _target_: lib.trainer.scheduler.OptimizerScheduler
  optimizer: ${optimizer.optimizer}
  optimizer_params: ${optimizer.optimizer_params}
  copy_optimizer_state: ${optimizer.copy_optimizer_state}
  milestones: ???
  params: ???

coarse2fine:
  _target_: lib.trainer.scheduler.CoarseToFineScheduler
  milestones: ???
  scales: ???