# base settings
datamodule: ???
optimizer: ???

scheduler:
  _target_: lib.trainer.scheduler.OptimizerScheduler
  copy_optimizer_state: False
  milestones: ???
  params: ???

coarse2fine:
  _target_: lib.trainer.scheduler.CoarseToFineScheduler
  milestones: ???
  scales: ???