# base settings
model: ???
datamodule: ???
logger: ???
optimizer: ???
loss: ???
camera: ???
rasterizer: ???

# logging settings
save_interval: 1
final_video: True

scheduler:
  _target_: lib.trainer.scheduler.OptimizerScheduler
  copy_optimizer_state: False
  milestones: ???
  params: ???

coarse2fine:
  _target_: lib.trainer.scheduler.CoarseToFineScheduler
  milestones: ???
  scales: ???