# @package joint_trainer

defaults:
  - defaults
  - _self_ 

_target_: lib.trainer.trainer.JointTrainer

# loop settings
init_idxs: [20,40]
max_iters: 5
max_optims: 3

scheduler:
  milestones: [0,1,2]
  params: [[global_pose,transl],[neck_pose,eye_pose],[shape_params,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]