# @package joint_trainer

_target_: lib.trainer.trainer.JointTrainer

model: ???
datamodule: ???
logger: ???
camera: ???
rasterizer: ???

# loop settings
init_idxs: [15,20,35,50,65,80,95,110]
max_iters: 100
max_optims: 5

optimizer:
  _target_: lib.trainer.scheduler.OptimizerScheduler
  milestones: [0,7,10,12]
  params: [[global_pose,transl],[neck_pose,eye_pose],[shape_params],[expression_params]]
  optimizer: ${trainer.optimizer}
  optimizer_params: ${trainer.optimizer_params}
  copy_optimizer_state: ${trainer.copy_optimizer_state}

coarse2fine:
  _target_: lib.trainer.scheduler.CoarseToFineScheduler
  milestones: [0]
  scales: [8]

# logging settings
save_interval: ${trainer.save_interval}

# convergence tests
check_convergence: ${trainer.check_convergence}
convergence_threshold: ${trainer.convergence_threshold}
min_tracker_steps: ${trainer.min_tracker_steps}
max_tracker_steps: ${trainer.max_tracker_steps}

