# @package joint_trainer

defaults:
  - defaults
  - _self_ 

_target_: lib.trainer.trainer.JointTrainer

# loop settings
init_idxs: [0,20,35,55,65,95,110,115]
max_iters: 50
max_optims: 50

scheduler:
  milestones: [0,10,15]
  params: [[global_pose,transl],[neck_pose,eye_pose],[shape_params,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]