# @package joint_trainer

defaults:
  - defaults
  - _self_ 

_target_: lib.trainer.trainer.JointTrainer

# loop settings
init_idxs: [0,20,35,55,65,95,110,115]
max_iters: 100
max_optims: 3 

scheduler:
  milestones: [0,20,40]
  params: [[global_pose,transl],[neck_pose,eye_pose],[shape_params,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]

default_params:
  transl: [0.0,0.0,-0.5]