_target_: lightning.pytorch.trainer.Trainer
default_root_dir: ${paths.output_dir}
min_epochs: 1 
max_epochs: 1000
accelerator: gpu 
devices: 1
check_val_every_n_epoch: 1
num_sanity_val_steps: 0
log_every_n_steps: 1
deterministic: False
overfit_batches: 1
# accumulate_grad_batches: 1