# @package pcg_sampling_trainer

defaults:
  - defaults
  - _self_ 

_target_: lib.trainer.trainer.PCGSamplingTrainer

# loop settings
max_samplings: 1000
init_idxs: [0]
max_iters: 1
max_optims: 1

scheduler:
  milestones: [0]
  params: [[global_pose,transl]]

coarse2fine:
  milestones: [0]
  scales: [8]