# @package sequential_trainer

defaults:
  - defaults
  - _self_ 


_target_: lib.trainer.trainer.SequentialTrainer

# loop settings
start_frame: 0
end_frame: 120
max_iters: 30
max_optims: 15

scheduler:
  milestones: [0,5]
  params: [[global_pose,transl,neck_pose,eye_pose],[expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]