# @package sequential_trainer

defaults:
  - defaults
  - _self_ 


_target_: lib.trainer.trainer.SequentialTrainer

# loop settings
start_frame: 21
end_frame: 24
max_iters: 4
max_optims: 3

scheduler:
  milestones: [0]
  params: [[global_pose,transl,neck_pose,eye_pose,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]