# @package sequential_trainer

defaults:
  - defaults
  - _self_ 


_target_: lib.trainer.trainer.SequentialTrainer

# loop settings
kernel_size: 1
stride: 1
dilation: 1
start_frame: 0
end_frame: 120
max_iters: 100
max_optims: 50

scheduler:
  milestones: [0]
  params: [[global_pose,transl,neck_pose,eye_pose,expression_params]]

coarse2fine:
  milestones: [0]
  scales: [8]