# @package weight_trainer

defaults:
  - defaults
  - _self_ 

_target_: lib.trainer.trainer.WeightingTrainer

# loop settings
init_idxs: [0]
train_steps: 10
lr: 1e-03
max_iters: 1
max_optims: 1
verbose: True

scheduler:
  milestones: [0]
  params: [[global_pose,transl]]

coarse2fine:
  milestones: [0]
  scales: [8]